version: 2
jobs:
  build:
    working_directory: ~/docgenerator
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
        command: |
          python setup.py install
      - run:
        command: |
          coverage run -m unittest
          coverage report
          coverage html
      - store_test_results:
        path: htmlcov
      - store_artifacts:
        path: htmlcov
        destination: cov1
